### ISSUE TITLE
Are pins 13 & 14 reversed on the counting register 74LS173?

### ISSUE THREAD

**Issue by MarkMaxPayne** [michaelkamprath/eater-sap-1-improvements#4]
Is it that the ICF and IZF input pins are reversed on the 74LS173?  It appears zero is driving ICF and carry is driving IZF in this diagram, no?  You could flip either pins 3&4 or pins 13&14, but flipping 13&14 would make the diagram look better.   

Best,
-Mark

**Comment by michaelkamprath** [comment]
Huh, yeah, you are right my schematic does reverse the output flags. I can say that my actual hardware implementation has this correct!  I'll fix the schematic in the repository.
